DROP TABLE IF EXISTS `league`;
CREATE TABLE IF NOT EXISTS `league` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    `city` varchar(64) NOT NULL,
    `conference` varchar(64) NOT NULL,
    `division` varchar(64) NOT NULL,
    `filename` varchar(256) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO `league` (`name`,`city`,`conference`, `division`, `filename`) VALUES
('Buffalo Bills', 'Buffalo', 'American Football Conference', 'AFC East', 'AFC_East.jpg'),
('Miami Dolphins', 'Miami', 'American Football Conference', 'AFC East', 'AFC_East.jpg'),
('New England Patriots', 'New England', 'American Football Conference', 'AFC East', 'AFC_East.jpg'),
('New York Jets', 'New York', 'American Football Conference', 'AFC East', 'AFC_East.jpg'),

('Baltimore Ravens', 'Baltimore', 'American Football Conference', 'AFC North', 'AFC_North.jpg'),
('Cincinnati Bengals', 'Cincinnati', 'American Football Conference', 'AFC North', 'AFC_North.jpg'),
('Cleveland Browns', 'Cleveland', 'American Football Conference', 'AFC North', 'AFC_North.jpg'),
('Pittsburgh Steelers', 'Pittsburgh', 'American Football Conference', 'AFC North', 'AFC_North.jpg'),

('Houston Texans', 'Houston', 'American Football Conference', 'AFC South', 'AFC_South.jpg'),
('Indianapolis Colts', 'Indianapolis', 'American Football Conference', 'AFC South', 'AFC_South.jpg'),
('Jacksonville Jaguars', 'Jacksonville', 'American Football Conference', 'AFC South', 'AFC_South.jpg'),
('Tennessee Titans', 'Tennessee', 'American Football Conference', 'AFC South', 'AFC_South.jpg'),

('Denver Broncos', 'Denver', 'American Football Conference', 'AFC West', 'AFC_West.jpg'),
('Kansas City Chiefs', 'Kansas City', 'American Football Conference', 'AFC West', 'AFC_West.jpg'),
('Oakland Raiders', 'Oakland', 'American Football Conference', 'AFC West', 'AFC_West.jpg'),
('San Diego Chargers', 'San Diego', 'American Football Conference', 'AFC West', 'AFC_West.jpg'),

('Dallas Cowboys', 'Dallas', 'National Football Conference', 'NFC East', 'NFC_East.jpg'),
('New York Giants', 'New York', 'National Football Conference', 'NFC East', 'NFC_East.jpg'),
('Philadelphia Eagles', 'Philadelphia', 'National Football Conference', 'NFC East', 'NFC_East.jpg'),
('Washington Redskins', 'Washington', 'National Football Conference', 'NFC East', 'NFC_East.jpg'),

('Chicago Bears', 'Chicago', 'National Football Conference', 'NFC North', 'NFC_North.jpg'),
('Detroit Lions', 'Detroit', 'National Football Conference', 'NFC North', 'NFC_North.jpg'),
('Green Bay Packers', 'Green Bay', 'National Football Conference', 'NFC North', 'NFC_North.jpg'),
('Minnesota Vikings', 'Minnesota', 'National Football Conference', 'NFC North', 'NFC_North.jpg'),

('Atlanta Falcons', 'Atlanta', 'National Football Conference', 'NFC South', 'NFC_South.jpg'),
('Carolina Panthers', 'Carolina', 'National Football Conference', 'NFC South', 'NFC_South.jpg'),
('New Orleans Saints', 'New Orleans', 'National Football Conference', 'NFC South', 'NFC_South.jpg'),
('Tampa Bay Buccaneers', 'Tampa Bay', 'National Football Conference', 'NFC South', 'NFC_South.jpg'),

('Arizona Cardinals', 'Arizona', 'National Football Conference', 'NFC West', 'NFC_West.jpg'),
('San Francisco 49ers', 'San Francisco', 'National Football Conference', 'NFC West', 'NFC_West.jpg'),
('Seattle Seahawks', 'Seattle', 'National Football Conference', 'NFC West', 'NFC_West.jpg'),
('St. Louis Rams', 'St. Louis', 'National Football Conference', 'NFC West', 'NFC_West.jpg');

DROP TABLE IF EXISTS `roster`;
CREATE TABLE IF NOT EXISTS `roster` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `surname` varchar(64) NOT NULL,
  `firstname` varchar(64) NOT NULL,
  `number` int(3) NOT NULL,
  `position` varchar(3) NOT NULL,
  `mugshot` varchar(64) NOT NULL,
   PRIMARY KEY (id)
);
INSERT INTO `roster` (`surname`, `firstname`, `number`, `position`, 
`mugshot`) VALUES
('Andrews', 'Antonio', 26, 'RB', 'temp-mug.png'),
('Bass', 'David', 51, 'LB', 'temp-mug.png'),
('Bell', 'Byron', 76, 'T', 'temp-mug.png'),
('Blackson', 'Angelo', 95, 'DT', 'temp-mug.png'),
('Brinkley', 'Beau', 48, 'LS', 'temp-mug.png'),
('Brown', 'Zach', 55, 'LB', 'temp-mug.png'),
('Casey', 'Jurrell', 99, 'DT', 'temp-mug.png'),
('Coffman', 'Chase', 85, 'TE', 'temp-mug.png'),
('Cox', 'Perrish', 29, 'CB', 'temp-mug.png'),
('Fasano', 'Harry', 80, 'TE', 'temp-mug.png'),
('Fowler', 'Jalston', 45, 'FB', 'temp-mug.png'),
('Gallik', 'Andy', 69, 'C', 'temp-mug.png'),
('Green-Beckham', 'Dorial', 17, 'WR', 'temp-mug.png'),
('Griffin', 'Michael', 33, 'S', 'temp-mug.png'),
('Hill', 'Sammie', 94, 'NT', 'temp-mug.png'),
('Huff', 'Marqueston', 28, 'DB', 'temp-mug.png'),
('Hunter', 'Justin', 15, 'WR', 'temp-mug.png'),
('Johnson', 'Steven', 52, 'MLB', 'temp-mug.png'),
('Jones', 'QaQuan', 90, 'DL', 'temp-mug.png'),
('Kern', 'Brett', 6, 'P', 'temp-mug.png'),
('Klug', 'Karl', 97, 'DL', 'temp-mug.png'),
('Lewan', 'Taylor', 77, 'P', 'temp-mug.png'),
('Mariota', 'Marcus', 8, 'DL', 'temp-mug.png'),
('Martin', 'Mike', 93, 'T', 'temp-mug.png'),
('McCluster', 'Dexter', 22, 'QB', 'temp-mug.png'),
('McCourty', 'Jason', 30, 'DL', 'temp-mug.png'),
('Meredith', 'Jamon', 79, 'RB', 'temp-mug.png'),
('Mettenberger', 'Zach', 7, 'CB', 'temp-mug.png'),
('Morgan', 'Derrick', 91, 'T', 'temp-mug.png'),
('Mount', 'Deiontrex', 53, 'QB', 'temp-mug.png'),
('Orakpo', 'Brian', 98, 'OLB', 'temp-mug.png'),
('Pitoitua', 'Ropati', 92, 'OLB', 'temp-mug.png'),
('Poutasi', 'Jeremiah', 72, 'OLB', 'temp-mug.png'),
('Riggs', 'Cody', 37, 'DE', 'temp-mug.png'),
('Sankey', 'Bishop', 20, 'T', 'temp-mug.png'),
('Schwenke', 'Brian', 62, 'RB', 'temp-mug.png'),
('Searcy', 'Da Narris', 21, 'C', 'temp-mug.png'),
('Sensabaugh', 'Coty', 24, 'S', 'temp-mug.png'),
('Spain', 'Quinton', 60, 'CB', 'temp-mug.png'),
('Stafford', 'Daimion', 39, 'G', 'temp-mug.png'),
('Stevens', 'Craig', 88, 'S', 'temp-mug.png'),
('Succop', 'Ryan', 4, 'T', 'temp-mug.png'),
('Supernaw', 'Phillip', 89, 'K', 'temp-mug.png'),
('Walker', 'Delanie', 82, 'TE', 'temp-mug.png'),
('Warmack', 'Chance', 70, 'TE', 'temp-mug.png'),
('West', 'Terrance', 35, 'G', 'temp-mug.png'),
('Whitehurst', 'Charlie', 12, 'RB', 'temp-mug.png'),
('Williamson', 'Avery', 54, 'QB', 'temp-mug.png'),
('Woods', 'Al', 96, 'LB', 'temp-mug.png'),
('Woodyard', 'Wesley', 59, 'DL', 'temp-mug.png'),
('Wreh-Wilson', 'Blidi', 25, 'LB', 'temp-mug.png'),
('Wright', 'Kendall', 13, 'CB', 'temp-mug.png');
