DROP TABLE IF EXISTS `league`;
CREATE TABLE IF NOT EXISTS `league` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL,
    `conference` varchar(64) NOT NULL,
    `division` varchar(64) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO `league` (`name`,`conference`, `division`) VALUES
('Buffalo Bills', 'American Football Conference', 'AFC East'),
('Miami Dolphins', 'American Football Conference', 'AFC East'),
('New England Patriots', 'American Football Conference', 'AFC East'),
('New York Jets', 'American Football Conference', 'AFC East'),

('Baltimore Ravens', 'American Football Conference', 'AFC North'),
('Cincinnati Bengals', 'American Football Conference', 'AFC North'),
('Cleveland Browns', 'American Football Conference', 'AFC North'),
('Pittsburgh Steelers', 'American Football Conference', 'AFC North'),

('Houston Texans', 'American Football Conference', 'AFC South'),
('Indianapolis Colts', 'American Football Conference', 'AFC South'),
('Jacksonville Jaguars', 'American Football Conference', 'AFC South'),
('Tennessee Titans', 'American Football Conference', 'AFC South'),

('Denver Broncos', 'American Football Conference', 'AFC West'),
('Kansas City Chiefs', 'American Football Conference', 'AFC West'),
('Oakland Raiders', 'American Football Conference', 'AFC West'),
('San Diego Chargers', 'American Football Conference', 'AFC West'),

('Dallas Cowboys', 'National Football Conference', 'NFC East'),
('New York Giants', 'National Football Conference', 'NFC East'),
('Philadelphia Eagles', 'National Football Conference', 'NFC East'),
('Washington Redskins', 'National Football Conference', 'NFC East'),

('Chicago Bears', 'National Football Conference', 'NFC North'),
('Detroit Lions', 'National Football Conference', 'NFC North'),
('Green Bay Packers', 'National Football Conference', 'NFC North'),
('Minnesota Vikings', 'National Football Conference', 'NFC North'),

('Atlanta Falcons', 'National Football Conference', 'NFC South'),
('Carolina Panthers', 'National Football Conference', 'NFC South'),
('New Orleans Saints', 'National Football Conference', 'NFC South'),
('Tampa Bay Buccaneers', 'National Football Conference', 'NFC South'),

('Arizona Cardinals', 'National Football Conference', 'NFC West'),
('San Francisco 49ers', 'National Football Conference', 'NFC West'),
(' Seattle Seahawks', 'National Football Conference', 'NFC West'),
('St. Louis Rams', 'National Football Conference', 'NFC West');

DROP TABLE IF EXISTS `roster`;
CREATE TABLE IF NOT EXISTS `roster` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `surname` varchar(64) NOT NULL,
  `firstname` varchar(64) NOT NULL,
  `number` int(3) NOT NULL,
  `position` varchar(3) NOT NULL,
  `mugshot` varchar(64) NOT NULL,
   PRIMARY KEY (id)
);
INSERT INTO `roster` (`surname`, `firstname`, `number`, `position`, 
`mugshot`) VALUES
('Andrews', 'Antonio', 26, 'RB', 'temp-mug.png'),
('Bass', 'David', 51, 'LB', 'temp-mug.png'),
('Bell', 'Byron', 76, 'T', 'temp-mug.png'),
('Blackson', 'Angelo', 95, 'DT', 'temp-mug.png'),
('Brinkley', 'Beau', 48, 'LS', 'temp-mug.png'),
('Brown', 'Zach', 55, 'LB', 'temp-mug.png'),
('Casey', 'Jurrell', 99, 'DT', 'temp-mug.png'),
('Coffman', 'Chase', 85, 'TE', 'temp-mug.png'),
('Cox', 'Perrish', 29, 'CB', 'temp-mug.png'),
('Fasano', 'Harry', 80, 'TE', 'temp-mug.png'),
('Fowler', 'Jalston', 45, 'FB', 'temp-mug.png'),
('Gallik', 'Andy', 69, 'C', 'temp-mug.png'),
('Green-Beckham', 'Dorial', 17, 'WR', 'temp-mug.png'),
('Griffin', 'Michael', 33, 'S', 'temp-mug.png'),
('Hill', 'Sammie', 94, 'NT', 'temp-mug.png'),
('Huff', 'Marqueston', 28, 'DB', 'temp-mug.png'),
('Hunter', 'Justin', 15, 'WR', 'temp-mug.png'),
('Johnson', 'Steven', 52, 'MLB', 'temp-mug.png'),
('Jones', 'QaQuan', 90, 'DL', 'temp-mug.png'),
('Kern', 'Brett', 6, 'P', 'temp-mug.png'),
('Klug', 'Karl', 97, 'DL', 'temp-mug.png'),
('Lewan', 'Taylor', 77, 'P', 'temp-mug.png'),
('Mariota', 'Marcus', 8, 'DL', 'temp-mug.png'),
('Martin', 'Mike', 93, 'T', 'temp-mug.png'),
('McCluster', 'Dexter', 22, 'QB', 'temp-mug.png'),
('McCourty', 'Jason', 30, 'DL', 'temp-mug.png'),
('Meredith', 'Jamon', 79, 'RB', 'temp-mug.png'),
('Mettenberger', 'Zach', 7, 'CB', 'temp-mug.png'),
('Morgan', 'Derrick', 91, 'T', 'temp-mug.png'),
('Mount', 'Deiontrex', 53, 'QB', 'temp-mug.png'),
('Orakpo', 'Brian', 98, 'OLB', 'temp-mug.png'),
('Pitoitua', 'Ropati', 92, 'OLB', 'temp-mug.png'),
('Poutasi', 'Jeremiah', 72, 'OLB', 'temp-mug.png'),
('Riggs', 'Cody', 37, 'DE', 'temp-mug.png'),
('Sankey', 'Bishop', 20, 'T', 'temp-mug.png'),
('Schwenke', 'Brian', 62, 'RB', 'temp-mug.png'),
('Searcy', 'Da Narris', 21, 'C', 'temp-mug.png'),
('Sensabaugh', 'Coty', 24, 'S', 'temp-mug.png'),
('Spain', 'Quinton', 60, 'CB', 'temp-mug.png'),
('Stafford', 'Daimion', 39, 'G', 'temp-mug.png'),
('Stevens', 'Craig', 88, 'S', 'temp-mug.png'),
('Succop', 'Ryan', 4, 'T', 'temp-mug.png'),
('Supernaw', 'Phillip', 89, 'K', 'temp-mug.png'),
('Walker', 'Delanie', 82, 'TE', 'temp-mug.png'),
('Warmack', 'Chance', 70, 'TE', 'temp-mug.png'),
('West', 'Terrance', 35, 'G', 'temp-mug.png'),
('Whitehurst', 'Charlie', 12, 'RB', 'temp-mug.png'),
('Williamson', 'Avery', 54, 'QB', 'temp-mug.png'),
('Woods', 'Al', 96, 'LB', 'temp-mug.png'),
('Woodyard', 'Wesley', 59, 'DL', 'temp-mug.png'),
('Wreh-Wilson', 'Blidi', 25, 'LB', 'temp-mug.png'),
('Wright', 'Kendall', 13, 'CB', 'temp-mug.png');
